import "@/styles/style.scss";
import Header from "@/components/ui/Header";
import Footer from '@/components/ui/Footer';

import type { Metadata } from "next";
export const metadata: Metadata = {
    title: "오느래 노래",
    description: "Generated by create next app",
    icons: {
        icon: '/icons/favicon.png'
    },
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
    return (
        <html lang="ko">
            <body>
                <Header />
                {children}
                <Footer/>
            </body>
        </html>
    );
}